<?php

namespace AppBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategorieIndex($catId = null){
        //$qb = $this->_em->createQueryBuilder()->from($this->_entityName, 'a')->select('a');
        // = -> $qb = $this->createQueryBuilder('a');

        $pub = 1;

        $qb = $this->createQueryBuilder('c');

        $qb ->leftJoin('c.articles','a')
                ->leftJoin('a.image','i')
                ->where('a.publication = :pub')
                ->setParameter('pub' ,$pub  )
                ->orderBy('c.titre')
                ->addSelect('a')
                ->addSelect('i')
                ;


        if ( $catId != null)
            $qb->andWhere('c.id = :catId')->setParameter('catId', $catId);



        $query = $qb->getQuery();
        return $query->getResult();
    }

}
